#pragma once

// response code 
#define SUCCESS_LOGIN 10
#define SUCCESS_CREATE_ROOM 20
#define SUCCESS_JOIN_ROOM 30
#define SUCCESS_SELL_ITEM 40
#define SUCCESS_BID_ITEM 50
#define CREATOR_CANT_BID_ITEM 51
#define INVALID_PRICE_BID 52
#define SUCCESS_BUY_IMMEDIATELY 60
#define CREATOR_CANT_BUY_ITEM 61
#define INVALID_PRICE_BUY 62
#define TIME_NOTIFICATION 70
#define SUCCESS_LEAVE_ROOM 90

//response code for noti user 
#define NOTI_ITEM_SOLD 80
#define NOTI_SUCCESS_CREATE_ROOM 82
#define NOTI_SUCCESS_JOIN_ROOM 83
#define NOTI_SUCCESS_SELL_ITEM 84
#define NOTI_SUCCESS_BID_ITEM 85
#define NOTI_SUCCESS_BUY_NOW 86
#define	NOTI_UPDATE_CURRENT_ITEM 87
#define NOTI_SUCCESS_LEAVE_ROOM 89

// error code 
#define SOMETHING_WRONG_WHEN_LOGIN 19
#define SOMETHING_WRONG_WHEN_CREATEROOM 29
#define SOMETHING_WRONG_WHEN_JOINROOM 39
#define SOMETHING_WRONG_WHEN_SELLITEM 59
#define SOMETHING_WRONG_WHEN_BIDITEM 69
#define SOMETHING_WRONG_WHEN_BUYNOW 79
#define SOMETHING_WRONG_WHEN_CONNECT 99

// opt code 
#define LOGIN 110
#define CREATEROOM 120
#define JOINROOM 130
#define SELLITEM 140
#define BIDITEM 150
#define BUYNOW 160
#define LEAVEROOM 170

// common variable
#define BUFF_SIZE 2048
#define HEADER_LENGTH 5